#! /bin/sh 
for f in "$1"/*; do
  if [ -f "$f" ]; then
    SIZE="$(du -sh "${f}" | cut -f 1)"
    word_count="$(wc -w "${f}" | cut -f 1 -d ' ')"
    echo "Processing $f file..."
    echo "File size: $SIZE"
    echo "Word count: $word_count"
  fi
done

